name: Run WebDriver Tests

on:
    push:

jobs:
    wdio:

        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3

            - name: Start server
              run: cd web && php -S 0.0.0.0:9000 -t ./ &

            - uses: actions/setup-node@v1
              with:
                node-version: 18

            - name: Install Node dependencies
              run: npm ci

            - name: Run Tests
              run: npm run test


